# -*- coding: utf-8 -*-
"""Converte Texto Arquivos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LctnhXR4MSMHz1_zFT4Wv7HE3ajML7ry
"""

import glob
from ftfy import fix_text

PATH_TEXT = "./text/dbd.puc-rio.br/sitenovo"
PATH_CONVERT = "./text/dbd.puc-rio.br/sitenovo/convertido"


def converter_texto(texto):
    texto_convertido = fix_text(texto)
    return texto_convertido

# Obter a lista de arquivos TXT na pasta
arquivos = glob.glob(f'{PATH_TEXT}/*.txt')

for arquivo_path in arquivos:
    # Obter o nome do arquivo sem o caminho
    nome_arquivo = arquivo_path.split('/')[-1]

    # Ler o arquivo de texto
    with open(arquivo_path, 'r', encoding='utf-8') as arquivo:
        texto_original = arquivo.read()

    # Converter o texto
    texto_convertido = converter_texto(texto_original)
    #print(texto_convertido)
    
    # Gerar o nome do novo arquivo
    novo_nome_arquivo = nome_arquivo.split('_')[-1]

    # Criar o novo caminho completo do arquivo
    novo_arquivo_path = f'{PATH_CONVERT}/{novo_nome_arquivo}'

    # Salvar o conteúdo convertido no novo arquivo
    with open(novo_arquivo_path, 'w', encoding='utf-8') as novo_arquivo:
        novo_arquivo.write(texto_convertido)

    print(f"Arquivo '{nome_arquivo}' convertido e salvo como '{novo_nome_arquivo}'.")

print("Conversão concluída.")